version: '3.8'

services:
  # 1. Redis: The high-speed queue
  redis:
    image: redis:alpine
    container_name: logstream_redis
    ports:
      - "6379:6379"
    restart: always

  # 2. MongoDB: The database
  mongo:
    image: mongo:latest
    container_name: logstream_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: